name: Daily Commit

on:
  schedule:
    - cron: '30 3 * * *'
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Modify log file by 24f2001743@ds.study.iitm.ac.in
        run: |
          echo "Daily update: $(date -u)" >> daily-log.txt

      - name: Commit and push changes
        run: |
          git config user.name "devsync-bot"
          git config user.email "24f2001743@ds.study.iitm.ac.in"
          git add daily-log.txt
          git commit -m "chore: daily update on $(date -u)" || echo "No changes to commit"
          git push origin HEAD

