name: Daily Commit

on:
  schedule:
    - cron: '30 3 * * *'
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Modify log file by 24f2001743@ds.study.iitm.ac.in
        run: |
          echo "Daily update: $(date -u)" >> daily-log.txt

      - name: Commit and Push Changes
        run: |
          git config --global user.name "devsync-bot"
          git config --global user.email "24f2001743@ds.study.iitm.ac.in"
          git add daily-log.txt
          git commit -m "chore: daily update on $(date -u)" || echo "Nothing to commit"
          git push
        env:
          # Use GitHub token to authorize push
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
